#!/bin/bash
case $1 in
    configure)
        /var/photobot/env3/bin/python /var/photobot/src/scripts/photobot_config.py --settings /var/photobot/config/photobot.ini
        ;;
    install)
        python /var/photobot/src/scripts/photobot_installer.py
        ;;
    update)
        echo "Updating Sources, Checking python dependencies and updating command script"
        cd /var/photobot/repo
        git pull
        /var/photobot/env2/bin/pip install -r /var/photobot/src/requirements2.txt
        /var/photobot/env3/bin/pip install -r /var/photobot/src/requirements3.txt
        /bin/cp -f /var/photobot/src/scripts/photobot /usr/bin
        chmod +x /usr/bin/photobot
        ;;
    usbrun)
        /var/photobot/env3/bin/python /var/photobot/src/photobot.py --settings /var/photobot/config/photobot.ini
        ;;
    ptzrun)
        /var/photobot/env2/bin/python /var/photobot/src/photobot_lorex.py --settings /var/photobot/config/photobot.ini
        ;;
    ptzsample)
        /var/photobot/env2/bin/python /var/photobot/src/photobot_lorex.py --settings /var/photobot/config/photobot.ini --send_high_res_sample 1
        ;;
    sample)
        /var/photobot/env3/bin/python /var/photobot/src/photobot.py --settings /var/photobot/config/photobot.ini --send_high_res_sample 1
        ;;
    powercycle)
        /var/photobot/env3/bin/python /var/photobot/src/powercycle.py --settings /var/photobot/config/photobot.ini
        ;;
    ais)
        /var/photobot/env3/bin/python /var/photobot/src/ais_receiver.py --settings /var/photobot/config/photobot.ini
        ;;
    thermal)
        /var/photobot/env3/bin/python /var/photobot/src/thermal_sample.py --settings /var/photobot/config/photobot.ini
        ;;
    tunnels)
        loclx tunnel --config /var/photobot/config/tunnels.yml
        ;;
    netsearch)
        /var/photobot/env3/bin/python /var/photobot/src/set_device_hostnames.py --settings /var/photobot/config/photobot.ini
        ;;
    run)
        /var/photobot/env2/bin/python /var/photobot/src/camrun.py --settings /var/photobot/config/photobot.ini --camera $2
        ;;
    samplecam)
        /var/photobot/env2/bin/python /var/photobot/src/camrun.py --settings /var/photobot/config/photobot.ini --camera $2 --send_high_res_sample 1
        ;;
    edit-config)
        /var/photobot/env3/bin/python /var/photobot/src/edit_yaml_config.py --settings /var/photobot/config/photobot.ini --which_config $2c
        ;;
    *)
        echo "
        -------Photobot Command Script--------
        Available commands are:

        sample - Take a sample image with the USB camera and upload it to the monitoring panel
        ptzsample - Take a sample image with the PTZ camera and upload it to the monitoring panel
        samplecam - Take a sample from an arbitrary camera usage samplecam CAMERA_NAME
        update - Update the source code to the latest version from the git repository
        configure - Run configuration script.
        install - Re-Run installation script. Useful for setting up new components, updating software etc.
        edit - Edit photobot.ini file using nano text editor
        usbrun - run a normal photo run with the usb camera
        ptzrun - run a normal run with the PTZ camera
        ais - run the AIS process and show output
        powercycle - test the power cycle (toggle relay state for 5 seconds)
        thermal - take a thermal photo and upload sample
        tunnels - start the ssh tunneling process to make devices available outside the local network
        netsearch - search the network for devices by MAC address and assign hostnames
        edit-config - Edit the modern style YAML config file with backups and syntax checks


        "
        ;;
esac
