#!/bin/bash
case $1 in
    configure)
        /var/photobot/env2/bin/python /var/photobot/src/scripts/photobot_config.py --settings /var/photobot/config/photobot.ini
        ;;
    install)
        python /var/photobot/src/scripts/photobot_installer.py
        ;;
    update)
        echo "Updating Source"
        cd /var/photobot/repo
        git pull
        ;;
    usbrun)
        /var/photobot/env2/bin/python /var/photobot/src/photobot.py --settings /var/photobot/config/photobot.ini
        ;;
    ptzrun)
        /var/photobot/env2/bin/python /var/photobot/src/photobot_lorex.py --settings /var/photobot/config/photobot.ini
        ;;
    sample)
        /var/photobot/env2/bin/python /var/photobot/src/photobot.py --settings /var/photobot/config/photobot.ini --send_high_res_sample 1
        ;;
    powercycle)
        /var/photobot/env2/bin/python /var/photobot/src/powercycle.py --settings /var/photobot/config/photobot.ini
        ;;
    ais)
        /var/photobot/env3/bin/python /var/photobot/src/ais_receiver.py --settings /var/photobot/config/photobot.ini
        ;;
    thermal)
        /var/photobot/env2/bin/python /var/photobot/src/thermal_sample.py --settings /var/photobot/config/photobot.ini
        ;;
    *)
        echo "
        -------Photobot Command Script--------
        Available commands are:

        sample - Take a sample image with the USB camera and upload it to the monitoring panel
        update - Update the source code to the latest version from the git repository
        configure - Run configuration script.
        install - Re-Run installation script. Useful for setting up new components, updating software etc.
        edit - Edit photobot.ini file using nano text editor
        usbrun - run a normal photo run with the usb camera
        ptzrun - run a normal run with the PTZ camera
        ais - run the AIS process and show output
        powercycle - test the power cycle (toggle relay state for 5 seconds)
        thermal - take a thermal photo and upload sample

        "
        ;;
esac
